import type {CompanyResponse} from '@/lib/domain/dashboard';
import {provenance, valueText} from './company-utils';

export function AuthorityDistribution({authority}: {authority: CompanyResponse['authority']}) {
  const entries = [['Backlinks', authority.backlinks], ['Referring domains', authority.referringDomains], ['Follow backlinks', authority.followBacklinks], ['No-follow backlinks', authority.noFollowBacklinks]] as const;
  const complete = entries.every(([, value]) => typeof value.value === 'number');
  if (!complete) return <section className="authority-distribution" aria-labelledby="authority-heading"><div className="company-module__heading"><div><h2 id="authority-heading">Authority</h2><p>Observed backlink metrics.</p></div></div><p className="company-module__unavailable">Authority detail is unavailable because the received subsection is incomplete.</p></section>;
  return <section className="authority-distribution" aria-labelledby="authority-heading"><div className="company-module__heading"><div><h2 id="authority-heading">Authority</h2><p>Observed backlink distribution; totals remain independently reported.</p></div></div><p className="authority-distribution__summary">{valueText(authority.backlinks)} backlinks and {valueText(authority.referringDomains)} referring domains are available.</p><div className="authority-distribution__chart" role="img" aria-label={`Authority distribution with ${valueText(authority.followBacklinks)} follow backlinks and ${valueText(authority.noFollowBacklinks)} no-follow backlinks`}><span>Follow {valueText(authority.followBacklinks)}</span><span>No-follow {valueText(authority.noFollowBacklinks)}</span></div><table className="company-table" aria-label="Authority distribution data"><thead><tr><th scope="col">Metric</th><th scope="col" className="company-table__numeric">Value</th><th scope="col">Provenance</th></tr></thead><tbody>{entries.map(([label, value]) => <tr key={label}><td>{label}</td><td className="company-table__numeric">{valueText(value)}</td><td>{provenance(value)}</td></tr>)}{authority.mozDomainAuthority ? <tr><td>Moz domain authority</td><td className="company-table__numeric">{valueText(authority.mozDomainAuthority)}</td><td>{provenance(authority.mozDomainAuthority)}</td></tr> : null}{authority.mozSpamScore ? <tr><td>Moz spam score</td><td className="company-table__numeric">{valueText(authority.mozSpamScore, 'percent')}</td><td>{provenance(authority.mozSpamScore)}</td></tr> : null}</tbody></table><div className="company-module__heading"><div><h3>Moz top pages</h3><p>Calculated validated URL sample.</p></div></div>{authority.mozTopPages?.length ? <table className="company-table" aria-label="Moz top pages"><thead><tr><th scope="col">Page</th><th scope="col" className="company-table__numeric">Page authority</th></tr></thead><tbody>{authority.mozTopPages.map((page) => <tr key={page.url}><td><a href={page.url} target="_blank" rel="noreferrer">Open page</a></td><td className="company-table__numeric">{valueText(page.pageAuthority)}</td></tr>)}</tbody></table> : <p className="company-module__unavailable">No validated Moz top-page sample is available.</p>}<p className="company-module__unavailable">Anchor text, backlink samples, linking-source samples, and AI cited-source domains are not available in the curated snapshot.</p></section>;
}
