'use client';

import {useEffect, useMemo, useState} from 'react';
import type {CompanySummary, DashboardValue, LandscapeResponse} from '@/lib/domain/dashboard';
import {KpiLedger, type KpiMetric} from '@/components/shared/KpiLedger';
import {ScreenState} from '@/components/shared/ScreenState';
import {AttentionSignals} from './AttentionSignals';
import {CompanyLeaderboard} from './CompanyLeaderboard';
import {clearLandscapeFilters, hasActiveFilters, parseLandscapeState, serializeLandscapeState, type LandscapeFilterState} from './filter-state';
import {LandscapeFilters} from './LandscapeFilters';
import {MarketMap} from './MarketMap';

const integer = new Intl.NumberFormat('en-US', {maximumFractionDigits: 0});
const comparison: Record<string, (company: CompanySummary) => number | boolean | null> = {authority: (c) => typeof c.authorityScore.value === 'number' ? c.authorityScore.value : null, traffic: (c) => typeof c.organicTraffic.value === 'number' ? c.organicTraffic.value : null, movement: (c) => typeof c.organicTraffic30DayMovement.value === 'number' ? c.organicTraffic30DayMovement.value : null, nonBrand: (c) => typeof c.nonBrandShare.value === 'number' ? c.nonBrandShare.value : null, keywords: (c) => typeof c.organicKeywords.value === 'number' ? c.organicKeywords.value : null, paid: (c) => typeof c.paidActivity.value === 'boolean' ? c.paidActivity.value : null, ai: (c) => typeof c.aiBenchmarkGap.value === 'number' ? c.aiBenchmarkGap.value : null, referring: (c) => typeof c.referringDomains.value === 'number' ? c.referringDomains.value : null};

function numeric(value: DashboardValue): number | null { return typeof value.value === 'number' ? value.value : null; }
function aggregate(companies: readonly CompanySummary[], get: (company: CompanySummary) => number | null): DashboardValue {
  const values = companies.map(get); const available = values.filter((value): value is number => value !== null);
  return {classification: 'calculated', value: available.length === values.length ? available.reduce((sum, value) => sum + value, 0) : null, coverage: {available: available.length, total: values.length}};
}
function count(companies: readonly CompanySummary[], predicate: (company: CompanySummary) => boolean | null): DashboardValue {
  const values = companies.map(predicate); const available = values.filter((value): value is boolean => value !== null);
  return {classification: 'calculated', value: available.length === values.length ? available.filter(Boolean).length : null, coverage: {available: available.length, total: values.length}};
}
function activeConstraints(state: LandscapeFilterState): string[] { return [state.paid && `paid activity is ${state.paid === 'unknown' ? 'not available' : state.paid}`, state.ai && `AI performance is ${state.ai.replace('_', ' ')}`, state.trafficMin !== undefined && `traffic at least ${integer.format(state.trafficMin)}`, state.trafficMax !== undefined && `traffic no more than ${integer.format(state.trafficMax)}`, state.authorityMin !== undefined && `authority at least ${integer.format(state.authorityMin)}`, state.authorityMax !== undefined && `authority no more than ${integer.format(state.authorityMax)}`, state.country && `country is ${state.country}`, state.segment && `segment is ${state.segment}`].filter((value): value is string => Boolean(value)); }

export function LandscapeScreen({initialData, initialSearch = ''}: {initialData: LandscapeResponse; initialSearch?: string}) {
  const parseOptions = useMemo(() => ({companyIds: new Set(initialData.companies.map((company) => company.companyId)), countries: new Set(initialData.filters.countries), segments: new Set(initialData.filters.segments)}), [initialData]);
  const [state, setState] = useState(() => parseLandscapeState(initialSearch, parseOptions));
  useEffect(() => { const restore = () => setState(parseLandscapeState(window.location.search, parseOptions)); window.addEventListener('popstate', restore); return () => window.removeEventListener('popstate', restore); }, [parseOptions]);
  const update = (change: Partial<LandscapeFilterState>) => setState((current) => { const next = {...current, ...change}; const query = serializeLandscapeState(next); if (typeof window !== 'undefined') window.history.pushState(null, '', query ? `?${query}` : window.location.pathname); return next; });
  const replace = (next: LandscapeFilterState) => { const query = serializeLandscapeState(next); if (typeof window !== 'undefined') window.history.pushState(null, '', query ? `?${query}` : window.location.pathname); setState(next); };
  const filtered = useMemo(() => initialData.companies.filter((company) => {
    const traffic = numeric(company.organicTraffic); const authority = numeric(company.authorityScore); const paid = company.paidActivity.value; const ai = numeric(company.aiBenchmarkGap);
    return (!state.paid || state.paid === 'active' && paid === true || state.paid === 'inactive' && paid === false || state.paid === 'unknown' && paid === null) && (!state.ai || state.ai === 'outperforming' && ai !== null && ai > 0 || state.ai === 'not_outperforming' && ai !== null && ai <= 0 || state.ai === 'unknown' && ai === null) && (state.trafficMin === undefined || traffic !== null && traffic >= state.trafficMin) && (state.trafficMax === undefined || traffic !== null && traffic <= state.trafficMax) && (state.authorityMin === undefined || authority !== null && authority >= state.authorityMin) && (state.authorityMax === undefined || authority !== null && authority <= state.authorityMax) && (!state.country || state.country === 'unknown' && !company.country || state.country === company.country) && (!state.segment || state.segment === 'unknown' && !company.segment || state.segment === company.segment);
  }), [initialData.companies, state]);
  const sorted = useMemo(() => { const [key, direction] = state.sort.split('-'); const get = comparison[key]!; return [...filtered].sort((left, right) => { const a = get(left); const b = get(right); if (a === null && b === null) return left.domain.localeCompare(right.domain); if (a === null) return 1; if (b === null) return -1; const order = (Number(a) - Number(b)) * (direction === 'asc' ? 1 : -1); return order || left.domain.localeCompare(right.domain); }); }, [filtered, state.sort]);
  const kpis: KpiMetric[] = [{label: 'Companies tracked', value: {classification: 'calculated', value: filtered.length}}, {label: 'Combined organic traffic', value: aggregate(filtered, (company) => numeric(company.organicTraffic))}, {label: 'Organic keyword footprint', value: aggregate(filtered, (company) => numeric(company.organicKeywords))}, {label: 'Growing companies', value: count(filtered, (company) => { const value = numeric(company.organicTraffic30DayMovement); return value === null ? null : value > 0; })}, {label: 'Paid active', value: count(filtered, (company) => company.paidActivity.value === null ? null : company.paidActivity.value === true)}];
  const mapRows = sorted.flatMap((company) => { const point = initialData.marketMap.find((candidate) => candidate.companyId === company.companyId); return point ? [{company, point}] : []; });
  const constraints = activeConstraints(state); const filtersActive = hasActiveFilters(state);
  const content = <><header className="landscape-heading"><div><h1 className="page-title">Competitive landscape</h1><p aria-live="polite" aria-atomic="true">{filtered.length} {filtered.length === 1 ? 'company' : 'companies'} across the selected market</p></div></header><LandscapeFilters state={state} countries={initialData.filters.countries} segments={initialData.filters.segments} paidAvailable={initialData.filters.paidActivityAvailable} aiAvailable={initialData.filters.aiPerformanceAvailable} active={filtersActive} onChange={update} onClear={() => replace(clearLandscapeFilters(state))} />{filtered.length === 0 ? <section className="landscape-empty" aria-labelledby="landscape-empty-heading"><h2 id="landscape-empty-heading">No companies match the active constraints</h2><p>{constraints.join('; ')}.</p></section> : <><div data-testid="landscape-kpis"><KpiLedger metrics={kpis} /></div><div className="landscape-modules"><MarketMap rows={mapRows} selectedCompany={state.selectedCompany} onSelect={(companyId) => update({selectedCompany: companyId})} /><AttentionSignals companies={sorted} signals={initialData.signals} /></div><CompanyLeaderboard companies={sorted} selectedCompany={state.selectedCompany} sort={state.sort} onSort={(sort) => update({sort})} onSelect={(companyId) => update({selectedCompany: companyId})} /></>}</>;
  const retained = initialData.companies.length > 0 && (initialData.status === 'stale' || initialData.status === 'partial' || initialData.status === 'failed' || initialData.status === 'running');
  return <ScreenState status={initialData.status} hasRetainedData={retained} recoveryMessage={initialData.recoveryMessage} announce={initialData.status !== 'succeeded'}>{content}</ScreenState>;
}
