'use client';

import type {DerivedMapRow} from './selectors';
const format = new Intl.NumberFormat('en-US', {maximumFractionDigits: 1});
function exactUtc(timestamp: string | null): string { const date = timestamp ? new Date(timestamp) : undefined; return date && !Number.isNaN(date.valueOf()) ? `${date.toISOString().slice(0, 16).replace('T', ' ')} UTC` : 'Not available'; }

export function MarketMap({rows, selectedCompany, onSelect}: {rows: readonly DerivedMapRow[]; selectedCompany?: string; onSelect: (companyId: string) => void}) {
  const available = rows.filter((row) => row.authorityScore !== null && row.authorityScore >= 0 && row.organicTraffic !== null && row.organicTraffic > 0 && row.trafficShare !== null && row.trafficShare > 0);
  const unavailableAxis = rows.filter((row) => row.authorityScore === null || row.authorityScore < 0 || row.organicTraffic === null).length;
  const zeroTraffic = rows.filter((row) => row.organicTraffic === 0).length;
  const unavailableShare = rows.filter((row) => row.authorityScore !== null && row.organicTraffic !== null && row.organicTraffic > 0 && (row.trafficShare === null || row.trafficShare <= 0)).length;
  const selectByIndex = (index: number, direction: number) => { const next = available[index + direction]; if (next) document.getElementById(`market-map-point-${next.company.companyId}`)?.focus(); };
  return <section className="market-map-panel" aria-labelledby="market-map-heading"><div className="landscape-panel-heading"><h2 id="market-map-heading">Authority and organic reach</h2><p>Authority score × organic traffic</p></div>
    <div className="market-map" data-testid="market-map" data-count={available.length} aria-label="Market map: authority score on the horizontal axis and organic traffic on the logarithmic vertical axis">
      <p className="market-map__axis market-map__axis--y">Organic traffic (logarithmic scale)</p><p className="market-map__axis market-map__axis--x">Authority score</p>
      <div className="market-map__plot">{available.map((row, index) => { const {company} = row; const descriptionId = `market-map-description-${company.companyId}`; const source = company.organicTraffic.source ?? company.authorityScore.source ?? 'Not available'; return <span key={company.companyId}><button id={`market-map-point-${company.companyId}`} type="button" className="market-map__point" data-selected={selectedCompany === company.companyId} data-ai-outperforming={row.aiBenchmarkGap !== null && row.aiBenchmarkGap > 0} style={{'--map-x': `${Math.min(100, row.authorityScore ?? 0)}%`, '--map-y': `${Math.max(4, 100 - ((Math.log10(row.organicTraffic ?? 1) / 8) * 100))}%`, '--map-size': `${Math.max(12, Math.min(44, (row.trafficShare ?? 0) * 60))}px`} as React.CSSProperties} aria-pressed={selectedCompany === company.companyId} aria-describedby={descriptionId} aria-label={`${company.displayName ?? company.domain}, ${company.domain}, authority ${format.format(row.authorityScore!)}, traffic ${format.format(row.organicTraffic!)}, tracked share ${format.format(row.trafficShare! * 100)}%, ${row.aiBenchmarkGap !== null ? `AI benchmark gap ${format.format(row.aiBenchmarkGap * 100)}%` : 'AI benchmark gap not available'}`} onClick={() => onSelect(company.companyId)} onKeyDown={(event) => { if (event.key === 'ArrowDown' || event.key === 'ArrowRight') { event.preventDefault(); selectByIndex(index, 1); } if (event.key === 'ArrowUp' || event.key === 'ArrowLeft') { event.preventDefault(); selectByIndex(index, -1); } }}>{company.displayName?.slice(0, 1) ?? company.domain.slice(0, 1)}</button><span id={descriptionId} className="visually-hidden">Source: {source}. Last successful refresh: {exactUtc(company.freshness.lastSuccessfulRunAt)}.</span></span>; })}</div>
    </div>
    <p className="market-map__note">{unavailableAxis || zeroTraffic || unavailableShare ? `${unavailableAxis} ${unavailableAxis === 1 ? 'company has' : 'companies have'} unavailable axis values; ${zeroTraffic} ${zeroTraffic === 1 ? 'has' : 'have'} zero organic traffic; ${unavailableShare} ${unavailableShare === 1 ? 'has' : 'have'} unavailable tracked-share values. These records are excluded from the logarithmic map.` : 'All filtered companies have complete market-map values.'}</p>
    <table className="market-map__data" aria-label="Market map accessible data"><thead><tr><th scope="col">Company</th><th scope="col">Authority</th><th scope="col">Organic traffic</th><th scope="col">Tracked share</th><th scope="col">AI benchmark gap</th><th scope="col">Source</th><th scope="col">Last successful refresh</th></tr></thead><tbody>{available.map((row) => <tr key={row.company.companyId}><th scope="row">{row.company.displayName ?? row.company.domain}</th><td>{format.format(row.authorityScore!)}</td><td>{format.format(row.organicTraffic!)}</td><td>{format.format(row.trafficShare! * 100)}%</td><td>{row.aiBenchmarkGap === null ? 'Not available' : `${format.format(row.aiBenchmarkGap * 100)}%`}</td><td>{row.company.organicTraffic.source ?? row.company.authorityScore.source ?? 'Not available'}</td><td>{exactUtc(row.company.freshness.lastSuccessfulRunAt)}</td></tr>)}</tbody></table>
  </section>;
}
